//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KhitrinovichUP1Texn
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestLog
    {
        public int log_id { get; set; }
        public Nullable<int> request_id { get; set; }
        public Nullable<System.DateTime> date_changed { get; set; }
        public string comment { get; set; }
    
        public virtual Request Request { get; set; }
    }
}
